fix NT matches not appearing in MyMonitor
foxtrick-ng/foxtrick pull request #30
Opened 2024-12-19 22:43 UTC by unnecessarydave

This was primarily failing because CHPP matches.xml is no longer supposed to be used for NT/U21 matches.

Technically NT matches are now HTO SourceSystem and when accessed via matches.xml the MatchType will be an HTO type.

The existing code has been hacked to work around this, but we should really be using nationalteammatches.xml for this.

2024-12-19 22:56 UTC, unnecessarydave commented
A side effect of this fix is that module NtPeek is also now working again:

![image](https://github.com/user-attachments/assets/b20391e8-ce70-4cd9-85a8-7103b5b7cc5a)

2024-12-21 20:17 UTC, murko69 commented
If I read the fix correct you disabled 'official' since it's the same as add senior?
Are you sure?

If I have 18 teams in monitor and chose official right now - only 17 games load, since 1 of the teams upcoming is a friendly, so official games is more like "competetive" games I guess.
In the Swedish translation I did that interpretation anyway and translated it as 'competition matches' instead of making a straight translation of the word official

2024-12-21 22:09 UTC, unnecessarydave commented
You were right the first time.  I had another look at the code, and as currently written Official would add League, Qualification, Cup and HT Masters for Senior teams only.

Updating that menu was one of the last changes I made.  I think I was pretty tired by then, saw that it was adding the same matches as Senior in my tests, and was happy to just disable it and call it a day.  Also the menu looks nicer without Official in there :)

I tested just now and it works, now that the friendlies are the next game.  I'll test it again later in the week as I can add Senior teams with a mix of friendly and qualification match then.

2024-12-22 10:22 UTC, foxtrick-ng requested changes
review requested by @murko69

2024-12-22 10:22 UTC, foxtrick-ng commented on content/information-aggregation/my-monitor.js
> +			//	'Official',
> If I read the fix correct you disabled 'official' since it's the same as add senior? Are you sure?

2024-12-22 10:23 UTC, murko69 commented
I also like it more without the 'Official' :)
Is your reason because 'less is more' or just because the wording is so wrong? 

Here's an 'what if' that is more than less :)

Since 'Official' only adds competitive games from Senior Team then you could move it up in the list and actually pair it with 'Senior'
Maybe like:

```
- select match type - 
-Senior Team-
All games
Competitive games only
Friendlies only
-Youth Team-
All games
-NT-
All games
Competitive games only
Friendlies only
```
Actually don't know if NT would ever need anything other than 'All games' since I have no clue if teams not in a cup/tournament are playing friendlies when other teams compete or if there is a 'friendly matches period' for all NTs?
But this is what I think would be possible to chose from in the import feature, right?

2024-12-22 11:16 UTC, unnecessarydave commented
> I also like it more without the 'Official' :) Is your reason because 'less is more' or just because the wording is so wrong?

Both.  It looks tidier and many users won't know what 'Official' means.


> ```
> - select match type - 
> -Senior Team-
> All games
> Competitive games only
> Friendlies only
> -Youth Team-
> All games
> -NT-
> All games
> Competitive games only
> Friendlies only
> ```
That would be the way to do it.  In fact I'd go further and split that into two.

However, it's not something I'd do in this PR.  Official will just have to sit at the bottom of the list for now.

The code/logic in MyMonitor needs a total rework, and I'm reluctant to hack at it much further beyond this basic fix I've done to patch it up.  I really like your ideas in #28 and we'd definitely change the menu/options presentation as a part of that.

2024-12-27 12:25 UTC, foxtrick-ng approved these changes

2025-01-07 17:35 UTC, merged